name: 'Telegram notify'
description: 'Sending text and files to telegram'
author: 'APS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'send'
  color: 'blue'

# Define your inputs here.
inputs:
  token:
    description: 'Token for bot acess'
    required: true

  to:
    description: 'Chat id for sending'
    required: true

  parse_mode:
    description: 'Parse mode: markdown or html'
    required: true
    default: 'HTML'

  message:
    description: 'Message text'
    required: false

  message_file:
    description: 'Message file'
    required: false

  document:
    description: 'Document'
    required: false

runs:
  using: node20
  main: dist/index.js
