name: 'Telegram notify ci-cd action'
description: 'Sending text and files to telegram'
author: 'APS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'send'
  color: 'blue'

# Define your inputs here.
inputs:
  token:
    description: 'Token for bot acess'
    required: true

  to:
    description: 'Chat id for sending'
    required: true

  parse_mode:
    description:
      'HTML, Markdown, MarkdownV2 (Telegram syntax), or CommonMark (automatic
      conversion to Telegram MarkdownV2)'
    required: true
    default: 'HTML'

  message:
    description: 'Message text'
    required: false

  message_file:
    description: 'Message file'
    required: false

  document:
    description: 'Document'
    required: false

outputs:
  message_ids:
    description: 'JSON array of successfully sent text message IDs'
  message_count:
    description: 'Number of successfully sent text messages'

runs:
  using: node24
  main: dist/index.js
