import { formatMarkdown } from '../src/markdown'
import { decodeFormattedMarkdown, splitMessage } from '../src/split'

const decode = (source: string): ReturnType<typeof decodeFormattedMarkdown> =>
  decodeFormattedMarkdown(formatMarkdown(source))

describe('CommonMark long messages', () => {
  it('preserves nested styles, code, links and escaped punctuation', () => {
    const message = decode(
      '**bold *italic*** and `a_b.c` [link](https://example.com/a_(b))!'
    )
    expect(message.text).toBe('bold italic and a_b.c link!')
    expect(message.entities).toEqual(
      expect.arrayContaining([
        { type: 'bold', offset: 0, length: 11 },
        { type: 'italic', offset: 5, length: 6 },
        { type: 'code', offset: 16, length: 5 },
        {
          type: 'text_link',
          offset: 22,
          length: 4,
          url: 'https://example.com/a_(b)'
        }
      ])
    )
  })

  it('preserves fenced code and quotes', () => {
    expect(decode('```cs\na_b`c\n```')).toEqual({
      text: 'a_b`c',
      entities: [{ type: 'pre', offset: 0, length: 5, language: 'cs' }]
    })
    expect(decode('> **hello**\n> world')).toEqual({
      text: 'hello\nworld',
      entities: [
        { type: 'bold', offset: 0, length: 5 },
        { type: 'blockquote', offset: 0, length: 11 }
      ]
    })
  })

  it('preserves issue links already generated by read_changelog_action', () => {
    const message = decode(
      'Fix ([#595](https://git.aps-m.com/APS_Soft/MIRAPS/issues/595)).'
    )
    expect(message.text).toBe('Fix (#595).')
    expect(message.entities).toEqual([
      {
        type: 'text_link',
        offset: 5,
        length: 4,
        url: 'https://git.aps-m.com/APS_Soft/MIRAPS/issues/595'
      }
    ])
  })
  it.each([4095, 4096, 4097, 9000])(
    'splits %i characters without loss',
    length => {
      const message = decode(`**${'x'.repeat(length)}**`)
      const parts = splitMessage(message)
      expect(parts.map(p => p.text).join('')).toBe(message.text)
      expect(parts).toHaveLength(Math.ceil(length / 4096))
      for (const part of parts) {
        expect(part.text.length).toBeLessThanOrEqual(4096)
        expect(part.entities).toEqual([
          { type: 'bold', offset: 0, length: part.text.length }
        ])
      }
    }
  )

  it('prefers item boundaries and preserves spaces and blank lines', () => {
    const message = decode(
      `# Title\n\n- ${'a'.repeat(2500)}\n- ${'b'.repeat(2500)}`
    )
    const parts = splitMessage(message)
    expect(parts).toHaveLength(2)
    expect(parts[0].text.endsWith('\n')).toBe(true)
    expect(parts[1].text.startsWith('• ')).toBe(true)
    expect(parts.map(p => p.text).join('')).toBe(message.text)
  })

  it('does not split emoji surrogate pairs', () => {
    const message = decode(`${'x'.repeat(4095)}😀y`)
    const parts = splitMessage(message)
    expect(parts.map(p => p.text)).toEqual(['x'.repeat(4095), '😀y'])
  })

  it('counts displayed text, not long URLs or escape characters', () => {
    expect(
      splitMessage(decode(`[a](https://example.com/${'x'.repeat(5000)})`))
    ).toHaveLength(1)
    expect(splitMessage(decode('!'.repeat(4096)))).toHaveLength(1)
  })

  it.each(['`', '```\n'])('preserves code across messages (%s)', marker => {
    const end = marker === '`' ? '`' : '\n```'
    const message = decode(marker + 'x'.repeat(6000) + end)
    const parts = splitMessage(message)
    expect(parts).toHaveLength(2)
    expect(
      parts
        .flatMap(p => p.entities)
        .every(e => e.type === (marker === '`' ? 'code' : 'pre'))
    ).toBe(true)
    expect(parts.map(p => p.text).join('')).toBe('x'.repeat(6000))
  })

  it('clips long links and nested styles correctly', () => {
    const message = decode(`[**${'x'.repeat(5000)}**](https://example.com)`)
    const parts = splitMessage(message)
    for (const part of parts) {
      expect(part.entities).toEqual(
        expect.arrayContaining([
          { type: 'bold', offset: 0, length: part.text.length },
          {
            type: 'text_link',
            offset: 0,
            length: part.text.length,
            url: 'https://example.com'
          }
        ])
      )
    }
  })
})
